### ISSUE TITLE
主页渲染不出来

### ISSUE THREAD

**Issue by evencewu** [General-Computer-Junkyard/djtu-wiki#1]
![image](https://github.com/user-attachments/assets/140646c8-3711-48d0-8f84-83a51047b527)
如上图

**Comment by neptune-T** [comment]
今早上维护手贱删了个文件,导致deploy.yml文件有bug,github渲染出问题了,只不过现在调整好了
https://general-computer-junkyard.github.io/djtu-wiki/
欢迎伍佬来玩来pr

**Comment by evencewu** [comment]
😄
